/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppModulesRouteImport } from './routes/app.modules'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAutocareIndexRouteImport } from './routes/app.autocare.index'
import { Route as AppCommerceIndexRouteImport } from './routes/app.commerce.index'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers.$customerId'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as AppEventsListRouteImport } from './routes/app.events.list'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'
import { Route as AppCommerceProductsIndexRouteImport } from './routes/app.commerce.products.index'
import { Route as AppCommerceProductsProductIdRouteImport } from './routes/app.commerce.products.$productId'
import { Route as AppCommerceProductsNewRouteImport } from './routes/app.commerce.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRoute = AppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAutocareIndexRoute = AppAutocareIndexRouteImport.update({
  id: '/autocare/',
  path: '/autocare/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommerceIndexRoute = AppCommerceIndexRouteImport.update({
  id: '/commerce/',
  path: '/commerce/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsListRoute = AppEventsListRouteImport.update({
  id: '/events/list',
  path: '/events/list',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCommerceProductsIndexRoute =
  AppCommerceProductsIndexRouteImport.update({
    id: '/commerce/products/',
    path: '/commerce/products/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCommerceProductsProductIdRoute =
  AppCommerceProductsProductIdRouteImport.update({
    id: '/commerce/products/$productId',
    path: '/commerce/products/$productId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCommerceProductsNewRoute = AppCommerceProductsNewRouteImport.update({
  id: '/commerce/products/new',
  path: '/commerce/products/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/activity': typeof AppActivityRoute
  '/app/modules': typeof AppModulesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/list': typeof AppEventsListRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/app/autocare/': typeof AppAutocareIndexRoute
  '/app/commerce/': typeof AppCommerceIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/commerce/products/$productId': typeof AppCommerceProductsProductIdRoute
  '/app/commerce/products/new': typeof AppCommerceProductsNewRoute
  '/app/commerce/products/': typeof AppCommerceProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/activity': typeof AppActivityRoute
  '/app/modules': typeof AppModulesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/list': typeof AppEventsListRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/app/autocare': typeof AppAutocareIndexRoute
  '/app/commerce': typeof AppCommerceIndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/commerce/products/$productId': typeof AppCommerceProductsProductIdRoute
  '/app/commerce/products/new': typeof AppCommerceProductsNewRoute
  '/app/commerce/products': typeof AppCommerceProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/app/activity': typeof AppActivityRoute
  '/app/modules': typeof AppModulesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/list': typeof AppEventsListRoute
  '/app/events/new': typeof AppEventsNewRoute
  '/app/autocare/': typeof AppAutocareIndexRoute
  '/app/commerce/': typeof AppCommerceIndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/commerce/products/$productId': typeof AppCommerceProductsProductIdRoute
  '/app/commerce/products/new': typeof AppCommerceProductsNewRoute
  '/app/commerce/products/': typeof AppCommerceProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/app/activity'
    | '/app/modules'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/customers/$customerId'
    | '/app/events/$eventId'
    | '/app/events/list'
    | '/app/events/new'
    | '/app/autocare/'
    | '/app/commerce/'
    | '/app/customers/'
    | '/app/events/'
    | '/app/commerce/products/$productId'
    | '/app/commerce/products/new'
    | '/app/commerce/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/app/activity'
    | '/app/modules'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/customers/$customerId'
    | '/app/events/$eventId'
    | '/app/events/list'
    | '/app/events/new'
    | '/app/autocare'
    | '/app/commerce'
    | '/app/customers'
    | '/app/events'
    | '/app/commerce/products/$productId'
    | '/app/commerce/products/new'
    | '/app/commerce/products'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/app/activity'
    | '/app/modules'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/customers/$customerId'
    | '/app/events/$eventId'
    | '/app/events/list'
    | '/app/events/new'
    | '/app/autocare/'
    | '/app/commerce/'
    | '/app/customers/'
    | '/app/events/'
    | '/app/commerce/products/$productId'
    | '/app/commerce/products/new'
    | '/app/commerce/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/modules': {
      id: '/app/modules'
      path: '/modules'
      fullPath: '/app/modules'
      preLoaderRoute: typeof AppModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/autocare/': {
      id: '/app/autocare/'
      path: '/autocare'
      fullPath: '/app/autocare/'
      preLoaderRoute: typeof AppAutocareIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commerce/': {
      id: '/app/commerce/'
      path: '/commerce'
      fullPath: '/app/commerce/'
      preLoaderRoute: typeof AppCommerceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/list': {
      id: '/app/events/list'
      path: '/events/list'
      fullPath: '/app/events/list'
      preLoaderRoute: typeof AppEventsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commerce/products/': {
      id: '/app/commerce/products/'
      path: '/commerce/products'
      fullPath: '/app/commerce/products/'
      preLoaderRoute: typeof AppCommerceProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commerce/products/$productId': {
      id: '/app/commerce/products/$productId'
      path: '/commerce/products/$productId'
      fullPath: '/app/commerce/products/$productId'
      preLoaderRoute: typeof AppCommerceProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commerce/products/new': {
      id: '/app/commerce/products/new'
      path: '/commerce/products/new'
      fullPath: '/app/commerce/products/new'
      preLoaderRoute: typeof AppCommerceProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppModulesRoute: typeof AppModulesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsListRoute: typeof AppEventsListRoute
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppAutocareIndexRoute: typeof AppAutocareIndexRoute
  AppCommerceIndexRoute: typeof AppCommerceIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppCommerceProductsProductIdRoute: typeof AppCommerceProductsProductIdRoute
  AppCommerceProductsNewRoute: typeof AppCommerceProductsNewRoute
  AppCommerceProductsIndexRoute: typeof AppCommerceProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppModulesRoute: AppModulesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsListRoute: AppEventsListRoute,
  AppEventsNewRoute: AppEventsNewRoute,
  AppAutocareIndexRoute: AppAutocareIndexRoute,
  AppCommerceIndexRoute: AppCommerceIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppCommerceProductsProductIdRoute: AppCommerceProductsProductIdRoute,
  AppCommerceProductsNewRoute: AppCommerceProductsNewRoute,
  AppCommerceProductsIndexRoute: AppCommerceProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
